### ISSUE TITLE
Question: when a lua state is dumped what form is it dumped in?

### ISSUE THREAD

**Issue by VaasKahnGrim** [Thomasims/GCrash#1]
Like say if I were wanting to read it as if I had opened a file in notepad++ would that be possible? also does it dump in a a single file, seperate files and is it only the area that caused a crash or is it the ENTIRITY of lua loaded into the server?

**Comment by Thomasims** [comment]
The dump is a text file with the lua stack trace at the time of the crash and whatever the lua handler decides to output. The default lua handler gives you every local and upvalue of the functions on the stack in string form, it helps figuring out why something crashed but I'd recommend writing your own handler to fit your needs.
