### ISSUE TITLE
Doesn't start after last Garry's Mod update

### ISSUE THREAD

**Issue by Flapchik** [Thomasims/GCrash#5]
I have been using GCrash for about 4 months now. After the last update of Garry's Mod, an error began to appear on one of the servers.
```
[ERROR] lua/autorun/server/gcrash.lua:3: Couldn't load module library!
  1. require - [C]:-1
   2. unknown - lua/autorun/server/gcrash.lua:3
```
```
require "gcrash"
```

**Comment by Thomasims** [comment]
I can't reproduce this on my own updated server. Try recompiling gcrash on your server.

**Comment by Flapchik** [comment]
I fixed the problem. The problem was that my server was on the x86-64 branch.
