### ISSUE TITLE
1.3.7 version

### ISSUE THREAD

**Issue by BeliyKrol** [Thomasims/GCrash#6]
Hi, 

It is possible to convert your's item to 1.3.7 version?
My hosting doesn't want to install 1.3.9
and I have this problem
[ERROR] lua/autorun/server/gcrash.lua:1: Couldn't load module library! (/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/server51814/game/garrysmod/lua/bin/gmsv_gcrash_linux.dll))
  1. require - [C]:-1
   2. unknown - lua/autorun/server/gcrash.lua:1

**Comment by Thomasims** [comment]
All the necessary build files are included in the repo, you can clone it and rebuild it on your machine with whatever std lib version your host uses.
